// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NeveTirzahPrison;

#nullable disable

namespace NeveTirzhaPrisoner.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231222011743_MigrationName")]
    partial class MigrationName
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("NeveTirzahPrison.Prisoner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DateBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Religion")
                        .HasColumnType("int");

                    b.Property<int>("YearsInPrison")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("prisoners");
                });

            modelBuilder.Entity("NeveTirzahPrison.PrisonGuard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<float>("HourlySalary")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("ShiftTime")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("prisonGuards");
                });

            modelBuilder.Entity("NeveTirzahPrison.RehabilitationPrograms", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<int>("LengthInMonths")
                        .HasColumnType("int");

                    b.Property<string>("Moderator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Programs")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("rehabilitationPrograms");
                });
#pragma warning restore 612, 618
        }
    }
}
