// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NeveTirzahPrison;

#nullable disable

namespace NeveTirzhaPrisoner.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240110200528_n2")]
    partial class n2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("NeveTirzahPrison.Prisoner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DateBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrisonGuardId")
                        .HasColumnType("int");

                    b.Property<int>("Religion")
                        .HasColumnType("int");

                    b.Property<int>("YearsInPrison")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PrisonGuardId");

                    b.ToTable("prisoners");
                });

            modelBuilder.Entity("NeveTirzahPrison.PrisonGuard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<float>("HourlySalary")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("ShiftTime")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("prisonGuards");
                });

            modelBuilder.Entity("NeveTirzahPrison.RehabilitationPrograms", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<int>("LengthInMonths")
                        .HasColumnType("int");

                    b.Property<string>("Moderator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PrisonerId")
                        .HasColumnType("int");

                    b.Property<int>("Programs")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PrisonerId");

                    b.ToTable("rehabilitationPrograms");
                });

            modelBuilder.Entity("NeveTirzahPrison.Prisoner", b =>
                {
                    b.HasOne("NeveTirzahPrison.PrisonGuard", "PrisonGuard")
                        .WithMany("prisoners")
                        .HasForeignKey("PrisonGuardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrisonGuard");
                });

            modelBuilder.Entity("NeveTirzahPrison.RehabilitationPrograms", b =>
                {
                    b.HasOne("NeveTirzahPrison.Prisoner", null)
                        .WithMany("Programs")
                        .HasForeignKey("PrisonerId");
                });

            modelBuilder.Entity("NeveTirzahPrison.Prisoner", b =>
                {
                    b.Navigation("Programs");
                });

            modelBuilder.Entity("NeveTirzahPrison.PrisonGuard", b =>
                {
                    b.Navigation("prisoners");
                });
#pragma warning restore 612, 618
        }
    }
}
